### ISSUE TITLE
fix algorithm when agent starts close to a box

### ISSUE THREAD

**Issue by JulesBelveze** [Otiosum/02285-ProgrammingProject#11]
<img width="604" alt="Screenshot 2019-05-14 at 14 34 07" src="https://user-images.githubusercontent.com/32683010/57698229-6c225d80-7655-11e9-9fd2-627297ce56e0.png">

The len of the solution here is 2 ... the agent stops after pushing the box twice...

<img width="443" alt="Screenshot 2019-05-14 at 14 37 17" src="https://user-images.githubusercontent.com/32683010/57698383-d63b0280-7655-11e9-86e4-56b9b4ee7e62.png">

**Comment by Otiosum** [comment]
i cant reproduce that.. it works for me. What did you change?
![image](https://user-images.githubusercontent.com/13841659/57698727-8dd01480-7656-11e9-9378-a3f9104f4bdd.png)

**Comment by JulesBelveze** [comment]
Well even when I pull from mergeInduction it does not work for me...

**Comment by JulesBelveze** [comment]
You are not using the right level..
The agent has to start close to the box. In your case he is one cell away from it

**Comment by Otiosum** [comment]
oh you changed the level

**Comment by JulesBelveze** [comment]
Yep, the first picture is the initial state

**Comment by Otiosum** [comment]
Try with this: 9ac06ed27d0a3fbada6fad5b1cd3909698231544

**Comment by JulesBelveze** [comment]
Looks like it is working. I'll check a bit more in-depth in an hour.
Keep you in touch
