### ISSUE TITLE
fix conflicts for action with MA

### ISSUE THREAD

**Issue by JulesBelveze** [Otiosum/02285-ProgrammingProject#9]
Switch action that is causing conflict to NoOp and recompute a new goal for the agent with the actual state as initial state

**Comment by JulesBelveze** [comment]
@Otiosum  need some help... I managed to recompute the goal for each agent when there is a conflict but I'm struggling to change the previous of actions by the new one... 

I attempted a stupid hack, that was to change all the remaining from the previous goal to NoOp and then append the new actions but I'm facing some issues...

PS: pay attention to all the `deepcopy` it is just to fix a weird problem...

**Comment by JulesBelveze** [comment]
Everything is pushed here [https://github.com/Otiosum/02285-ProgrammingProject/commit/9c675497cff4206faddda62ca6ed4067f55284d6](url)

**Comment by JulesBelveze** [comment]
New attempt in e21420668daaff5e418977e46f88a52c99fba466 by removing the `deepcopy`s in `check_action`

**Comment by Otiosum** [comment]
But what you do now in the new attempt is not copying states right? You are just assigning next_state to current. If you want to copy them you should do: next_state = State(current_state)

**Comment by JulesBelveze** [comment]
My bad, I forgot it yes (fix in: 59de872). But it doesn't solve the problem though... :(

**Comment by JulesBelveze** [comment]
temporary hack in 1a49593

**Comment by Otiosum** [comment]
You merged with refactor agent branched?

**Comment by JulesBelveze** [comment]
Yes !

**Comment by JulesBelveze** [comment]
fixed in 50b390d
